import random

import requests
from dynaconf import Dynaconf

from backends.common import FunctionClient
from backends.kernel.requestclient import RequestClient

MYSQL_CONFIG = {
    'host': '',
    'port': 3306,
    'user': '',
    'password': '',
    'database': '',
    'charset': 'utf8mb4'
}

FEISHU_APP_ID = ''

FEISHU_APP_SECRET = ''

WS_ADDRESS_A = ''  # ws://172.0.0.0:3698

WS_ADDRESS_B = ''

ALIYUN_API_KEY = ''

ALIYUN_API_SECRET = ''

ALIYUN_POINT = 'ap-northeast-1'

WEB_ADDRESS = ''  # 172.0.0.0

CANCEL_WEB_ADDRESS = ''  # 172.0.0.0

settings = Dynaconf(
    envvar_prefix='DYNACONF',
    settings_files=['settings.yaml', '.secrets.yaml'],

    MYSQL_CONFIG=MYSQL_CONFIG,

    FEISHU_APP_ID=FEISHU_APP_ID,
    FEISHU_APP_SECRET=FEISHU_APP_SECRET,

    WS_ADDRESS_A=WS_ADDRESS_A,  # ws://172.0.0.0:3698
    WS_ADDRESS_B=WS_ADDRESS_B,

    ALIYUN_API_KEY=ALIYUN_API_KEY,
    ALIYUN_API_SECRET=ALIYUN_API_SECRET,
    ALIYUN_POINT=ALIYUN_POINT,

    WEB_ADDRESS=WEB_ADDRESS,  # 172.0.0.0
    CANCEL_WEB_ADDRESS=CANCEL_WEB_ADDRESS,  # 172.0.0.0
)
FUNCTION_CLIENT = FunctionClient(larkMsgSymbol='secondOpen')
PUBLIC_SERVER_IP = 'http://' + settings.WEB_ADDRESS + ':8888/'
PRIVATE_IP = FUNCTION_CLIENT.get_private_ip()
SERVER_NAME = FUNCTION_CLIENT.getServerName()
BINANCE_API_KEY = ''
BINANCE_API_SECRET = ''
ORDER_TABLE_NAME = ''
ORDER_ID_SYMBOL = 'm'
ORDER_ID_INDEX = random.randint(1, 100000)
response = requests.request('POST', PUBLIC_SERVER_IP + 'get_symbol_index', timeout=3).json()
TRADE_SYMBOL_ARR = response['d']
ONE_MIN_KLINE_OBJ_ARR = []
LOCAL_ONE_MIN_KLINE_OBJ_ARR = []
LAST_OPEN_PRICE = []
LAST_OPEN_RATE_ARR = []
OPEN_POSITION_TS_ARR = []
ADD_POSITION_TS_ARR = []
OPEN_TIME_ARR = []
TAKE_OPEN_TIME_ARR = []
LAST_ORDER_INFO_ARR = []
DEPTH_PRICE_ARR = []
OPEN_DIRECTION_ARR = []
SYMBOL_OPEN_TYPE_ARR = []
SYMBOL_STANDARD_VALUE_ARR = []
SPECIAL_CLOSE_POSITION_ARR = []
POSITION_ARR = []
ACCOUNT_BALANCE_VALUE = 0
BAN_SYMBOL_ARR = []
SYMBOL_STOP_LOSS_TS_ARR = []
LAST_DATA_STR = ''
UPDATE_DATA_STR = False
LAST_DATA_UPDATE_TS = 0
LAST_NEW_OPEN_TS = 0
LAST_UPDATE_TRADE_STATUS_TS = 0
UPDATE_ONE_DAY_RATE_TS = 0
SYMBOL_STOP_TRADE_WARN_TS_OBJ = {}
RUN_TIME = 0
BIG_LOSS_LIMIT_TS = 0
STANDARD_TRADE_VALUE = 1000
UPDATE_VOL_TS = 0
STOP_OPEN_LONGS_BY_TOO_MANY_FIT_TS = 0
STOP_OPEN_SHORTS_BY_TOO_MANY_FIT_TS = 0
UPDATE_ACCOUNT_BALANCE_VALUE_TS = 0
BTC_NOW_OPEN_RATE = 0
ETH_NOW_OPEN_RATE = 0
SPECIAL_MODE = False
REQUEST_CLIENT = RequestClient(api_key=BINANCE_API_KEY, secret_key=BINANCE_API_SECRET)
PRICE_DECIMAL_OBJ = {}
AMOUNT_DECIMAL_OBJ = {}
PRICE_TICK_OBJ = {}
PRICE_DECIMAL_AMOUNT_OBJ = {}
AMOUNT_DECIMAL_AMOUNT_OBJ = {}
MARKET_MAX_SIZE_OBJ = {}
MARKET_MIN_SIZE_OBJ = {}
BALANCE_WARN_TS = 0
ONCE_TRADE_VALUE = 0
